### ISSUE TITLE
Anyway to limit the total number of pages crawled or shutdown the crawler after some criteria?

### ISSUE THREAD

**Issue by samur-vonq** [postmodern/spidr#40]

**Comment by postmodern** [comment]
Use [every_page](http://www.rubydoc.info/gems/spidr/Spidr/Events#every_page-instance_method) and check [queue.length](http://www.rubydoc.info/gems/spidr/Spidr/Agent#queue-instance_method).

**Comment by postmodern** [comment]
See also [Actions](www.rubydoc.info/gems/spidr/Spidr/Actions) which are included into [Agent](www.rubydoc.info/gems/spidr/Spidr/Agent).
