### ISSUE TITLE
Is it possible to display only part of a spidered URL?

### ISSUE THREAD

**Issue by DHarls17** [postmodern/spidr#41]
I only want to display part of a spidered URL, but is this possible?

I've spidered the website www.parkers.co.uk and got the correct URLs, but I don't want to displayed the www.parkers.co.uk part of the URL.

For example, instead of;
http://www.parkers.co.uk/cars/prices/
http://www.parkers.co.uk/cars/leasing/
http://www.parkers.co.uk/vans/for-sale/

I just want to display;
/cars/prices/
/cars/leasing/
/vans/for-sale/

thanks!

**Comment by robfuller** [comment]
page.url is a URI object, so you can just call .path on it to get what you are looking for.

**Comment by postmodern** [comment]
Please see the [URI::HTTP](http://www.rubydoc.info/stdlib/uri/URI/HTTP) API docs. I'm almost certain what you're looking for is the `request_uri` method, which returns path + fragment + query.

**Comment by postmodern** [comment]
You can find all documentation for ruby's stdlib in http://rubydoc.info/stdlib/ and all gem documentation at http://rubydoc.info/gem/name_goes_here. Cheers
