### ISSUE TITLE
Crawling a specific page

### ISSUE THREAD

**Issue by justaj** [postmodern/spidr#46]
Hey!  I was wondering if there was a way to return all links found on a specific page.  So far spidr has been great for crawling a whole site but with my testing I'd like to be able to focus on one page.

Thanks

**Comment by postmodern** [comment]
You could use `every_page { |page| ... }` and filter `page.url` for the page you are looking for? Also, you could use [visit_urls_like](http://www.rubydoc.info/gems/spidr/Spidr/Agent#visit_urls_like-instance_method) to only visit that specific page.

**Comment by postmodern** [comment]
Oh, you could also manually request the page via net-http, mechanize, RestClient, etc and manually create a [Spidr::Page](www.rubydoc.info/gems/spidr/Spidr/Page#initialize-instance_method) object.
