### ISSUE TITLE
How to control the depth of crawling?

### ISSUE THREAD

**Issue by masterbo98** [postmodern/spidr#82]
When I user spidr, I find it really helpful and efficient. At present, I want to shorten the crawling time, is there any way or API to set the depth of spidr?

**Comment by postmodern** [comment]
You can use the `max_depth:` keyword argument which can be passed to `Agent.start_at,` .Agent.host`, `Agent.site`, and `Agent#initialize`.
https://rubydoc.info/gems/spidr/Spidr/Agent#initialize-instance_method
